name: Build Android APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - parlourease-admin
          - parlourease-client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.app }}/package-lock.json

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        working-directory: ${{ matrix.app }}
        run: npm ci

      - name: Build web (Next.js export)
        working-directory: ${{ matrix.app }}
        run: npm run export

      - name: Copy web to Android (Capacitor)
        working-directory: ${{ matrix.app }}
        run: npx cap copy android

      - name: Make Gradle executable
        working-directory: ${{ matrix.app }}/android
        run: chmod +x gradlew

      - name: Build debug APK
        working-directory: ${{ matrix.app }}/android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-debug-apk
          path: ${{ matrix.app }}/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
